### PR TITLE
Make cells clickable

### PR DESCRIPTION
**Pull request by MattMcNam**
Added a prop to handle cells being clicked, to avoid needing to write a custom cell renderer for each column.

Callback is provided with the full row data and the name of the column that the cell is under

### CODE REVIEW

**Comment by techniq** [comment]
@MattMcNam Seems like a good addition.  A couple thoughts/questions before I merge:

We currently have a `onHeaderClick` as well (which I'm sure you've seen).  The problem is where `onCellClick` is applied on the `TableCell` while `onHeaderClick` is applied within the `TableCell` on the `TableSortLabel` component (which matches the interactions in Material UI's [docs](https://material-ui-next.com/demos/tables/#sorting-amp-selecting)).  This causes both events to fire when clicking on a header cell's label.

```js
return (
      <TableCell
        component="div"
        className={className}
        key={key}
        onClick={() => onCellClick && onCellClick(rowData, column.name)}
        style={{ ...style, ...cellStyle }}
        {...cellProps}
      >
        { isHeader ? (
          <TableSortLabel
            active={orderBy && orderBy === column.name && rowIndex === 0}
            direction={orderDirection}
            onClick={() => onHeaderClick && onHeaderClick(column)}
          >
            {contents}
          </TableSortLabel>
        ) : (
          contents
        )}
      </TableCell>
    )
```
Initially I thought we could just move `onHeaderClick` up to the `TableCell` and conditionally apply based on the cell, such as...

```js
<TableCell
  onClick={() => isHeader ?
    (onHeaderClick && onHeaderClick(column)) :
    (onCellClick && onCellClick(rowData, column.name))}
</TableCell>
```

...but then you won't get the hover feedback for the label when you hover over just the cell (but outside the label).

For header rows, `rowData` will be null, so we could handle this when wiring up handlers (if you know this at least).

```js
<MuiTable
  onHeaderClick={() => alert('headerClick')}
  onCellClick={(data, name) => data && alert(`onCellClick ${data} - ${name}`)}
/>
```

My questions are:
- Does this seem reasonable to have the 2 handlers work in this fashion?
- It seems like we should go ahead and pass the whole `column` definition in `onCellClick`, to be consistent with `onHeaderClick` and in case there is additional data attached to the definition that could be useful at the cell level.  For header rows, I'll sometimes add a `orderBy` property, for example.
  - `onClick={() => onCellClick && onCellClick(rowData, column)}`
- Could you add an entry to the `README` to document this prop

Thanks for this contirbution

**Comment by MattMcNam** [comment]
Thanks for the feedback!

`onCellClick` passing null as it's data feels odd, though for whatever reason it feels less odd if the arguments are swapped to `(column, data)` and documented as null on headers?
I'll play around with headers for a bit, wasn't using them when I made this PR.

Agreed on passing in full column object, I'll change that and update the README.

**Comment by techniq** [comment]
We could maybe augment the column definition with "isHeader" or pass it as
a third argument to onCellClick ... Just some thoughts.

**Comment by techniq** [comment]
@MattMcNam I implemented this in `0.1.1`

I decided to only call `onCellClick` for non-header rows, and pass `(column, rowData)` to the callback (so you can pull the cell data using `rowData[column.name]`).  You can still using `onHeaderClick` separately (which only receives the `column` definition)

**Comment by techniq** [comment]
I also added support for `cellProps` passed to `Table`, so you could also technically add a global `onClick` to all cells (header or otherwise), but this being simple `onClick` added to [TableCell](https://material-ui-next.com/api/table-cell/) it will only receive the standard click event.

```js
<Table
  cellProps={{ onClick: e => alert('Cell clicked') }}
/>
```

The `cellProps` were added mostly to set the other props (`padding`, etc) but thought it was worth pointing out.  You can also add cellProps on a per column (including header), where you would know the column, but you would have to do more work inside onClick and the entire `data` to find what you likely wanted to use

```js
<MuiTable
  data={data}
  columns={[
    { name: 'fullName', cellProps: { onClick(e) { alert(e.target.innerText) }}},
    { name: 'jobTitle', header: 'Job Title' },
    { name: 'jobArea', header: 'Job Area' },
  ]}
/>

**Pull request closed without merging**
